### ISSUE TITLE
"Unknown column 'Favorite Gun' in 'field list'"

### ISSUE THREAD

**Issue by LeSauvage** [11TStudio/SquadStatJS#16]
New Fresh install, new database. I am not sure why this is happening

```
C:\SquadStatJS\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'Favorite Gun' in 'field list'
    at Query.Sequence._packetToError (C:\SQc\SquadStatJS\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\SQc\SquadStatJS\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\SQc\SquadStatJS\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\SQc\SquadStatJS\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\SQc\SquadStatJS\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\SQc\SquadStatJS\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\SQc\SquadStatJS\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\SQc\SquadStatJS\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (C:\SquadStatJS\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\SquadStatJS\node_modules\mysql\lib\Connection.js:198:25)
    at Handshake.<anonymous> (C:\SquadStatJS\comms\search.js:64:21)
    at Handshake.<anonymous> (C:\SquadStatJS\node_modules\mysql\lib\Connection.js:526:10)
    at Handshake._callback (C:\SquadStatJS\node_modules\mysql\lib\Connection.js:488:16)
    at Handshake.Sequence.end (C:\SquadStatJS\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Handshake.Sequence.OkPacket (C:\SquadStatJS\node_modules\mysql\lib\protocol\sequences\Sequence.js:92:8)
    at Protocol._parsePacket (C:\SquadStatJS\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\SquadStatJS\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\SquadStatJS\node_modules\mysql\lib\protocol\Parser.js:43:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'Favorite Gun' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT m.attacker AS 'Steam_ID', `Name`, `Wounds`,`Kills`,`Deaths`,`Kills`/`Deaths` AS `K/D`,`Revives`,m.id AS 'ID', `TeamKills`, `Favorite Gun`, `Favorite Role` FROM `PlayerWounded` m LEFT JOIN ( SELECT attacker, COUNT(*) AS `Wounds` FROM `PlayerWounded` WHERE server IN (1) GROUP BY attacker ORDER BY time ASC) w ON w.attacker = m.attacker JOIN (SELECT attacker, weapon AS `Favorite Role`, COUNT(weapon) FROM PlayerWounded WHERE attacker = 76561198024256439 GROUP BY weapon ORDER BY COUNT(weapon) DESC) fw ON fw.attacker = m.attacker LEFT JOIN (SELECT attacker, COUNT(*) AS `TeamKills` FROM `PlayerDied` WHERE server = 1 AND teamkill = 1 GROUP BY attacker) tk ON tk.attacker = m.attacker JOIN (SELECT attacker, weapon AS `Favorite Role`, COUNT(weapon) FROM PlayerDied WHERE attacker = 76561198024256439 GROUP BY weapon ORDER BY COUNT(weapon) DESC) fg ON fg.attacker = m.attacker LEFT JOIN (SELECT attacker, COUNT(*) AS `Kills` FROM `PlayerDied` WHERE server IN (1)  GROUP BY attacker) k ON k.attacker = m.attacker LEFT JOIN ( SELECT victim, COUNT(*) AS `Deaths` FROM `PlayerDied` WHERE server IN (1) GROUP BY victim) d ON d.victim = m.attacker LEFT JOIN (SELECT steamID, lastName AS `Name` FROM `SteamUser`) s ON s.steamID = m.attacker LEFT JOIN ( SELECT reviver, COUNT(*) AS `Revives` FROM `PlayerRevived` WHERE server IN (1) GROUP BY reviver ) r ON r.reviver = m.attacker WHERE steamID = '76561198024256439' AND server IN (1)  GROUP BY m.attacker HAVING `K/D` IS NOT NULL ORDER BY `K/D` DESC, time DESC"
}
```

**Comment by LeventHAN** [comment]
Fixed the issue... It was my fault when fixing the roles and guns I did forget to change the Role to Gun on one of the copy querrys
Use this fix: https://github.com/11TStudio/SquadStatJS/commit/94187202684015515f3c2e96a78d9a9fcee70e98 right in your code or just reclone the project  (or git fetch it...)
